In [13]:
import numpy as np

A = np.array([[complex(1,0)], [complex(0,0)]])
B = np.array([[complex(1,0)], [complex(0,0)]])

C = np.kron(A,B)

print(C)


[[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]


In [8]:
import numpy as np

def controlled_x_gate_kron(num_qubits, control, target):
    """
    Create a C_i X_j gate matrix using Kronecker product for num_qubits qubits.

    Parameters:
    num_qubits (int): Total number of qubits.
    control (int): The index of the control qubit (0-based).
    target (int): The index of the target qubit (0-based).

    Returns:
    numpy.ndarray: The 2^num_qubits x 2^num_qubits matrix representing the C_i X_j gate.
    """
    # Define basic gate matrices
    I = np.array([[1, 0], [0, 1]], dtype=complex)  # Identity matrix
    X = np.array([[0, 1], [1, 0]], dtype=complex)  # Pauli-X matrix
    zero_proj = np.array([[1, 0], [0, 0]], dtype=complex)  # |0><0| projector
    one_proj = np.array([[0, 0], [0, 1]], dtype=complex)   # |1><1| projector

    # Create the identity matrix for control qubit being |0>
    control_zero = [I] * num_qubits
    control_zero[control] = zero_proj  # Projector for |0> state at control qubit
    control_zero_gate = control_zero[0]
    for mat in control_zero[1:]:
        control_zero_gate = np.kron(control_zero_gate, mat)

    # Create the gate for control qubit being |1> and applying X on target
    control_one = [I] * num_qubits
    control_one[control] = one_proj  # Projector for |1> state at control qubit
    control_one[target] = X  # X gate at target qubit
    control_one_gate = control_one[0]
    for mat in control_one[1:]:
        control_one_gate = np.kron(control_one_gate, mat)

    # Sum the two matrices
    full_gate = control_zero_gate + control_one_gate

    return full_gate

# Example usage:
num_qubits = 3
control_qubit = 0
target_qubit = 2
cx_gate_kron = controlled_x_gate_kron(num_qubits, control_qubit, target_qubit)
print(cx_gate_kron)


Control_zero: [array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]]), array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]]), array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])]
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j]]


In [28]:
import numpy as np

def swap_gate(n, i, j):
    low = [
        np.array([[1,0],[0,0]]),
        np.array([[0,0],[1,0]]),
        np.array([[0,1],[0,0]]),
        np.array([[0,0],[0,1]]),
    ]
    high = [
        np.array([[1,0],[0,0]]),
        np.array([[0,1],[0,0]]),
        np.array([[0,0],[1,0]]),
        np.array([[0,0],[0,1]]),
    ]

    if (i > j):
        i, j = j, i
    
    I = np.array([[1,0],[0,1]])

    gate = 0
    for phase in range(4):
        quater_gate = 1
        for idx in range(n):
            if (idx == i):
                quater_gate = np.kron(low[phase], quater_gate)
            elif (idx == j):
                quater_gate = np.kron(high[phase], quater_gate)
            else:
                quater_gate = np.kron(I, quater_gate)
        gate += quater_gate

    return gate


# 예제: 3개의 큐빗에서 0번과 2번 큐빗을 스왑하는 스왑 게이트
swap_3q = swap_gate(4, 0, 1)
print("3-큐빗 시스템의 0번과 2번 큐빗 스왑 게이트 행렬:")
print(swap_3q)


NameError: name 'qc' is not defined

In [31]:
size = 3

base = np.eye(2**size)

print(base)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
